version: "3.9"

services:
  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      CORS_ALLOWED_ORIGINS: http://${HOST}:${FRONTEND_PORT}
    restart: always
    image: typing_world_backend:${VERSION}
    container_name: typing_world_backend-${VERSION}
    volumes:
      - ./backend/:/code
    ports:
      - "${BACKEND_PORT}:8000"
  frontend:
    build:
      context: ./frontend
      args:
        - VUE_APP_API_BASE_ADDRESS=http://${HOST}:${BACKEND_PORT}/api
    env_file:
      - .env
    restart: always
    image: typing_world_fronted:${VERSION}
    container_name: typing_world_fronted-${VERSION}
    ports:
      - "${FRONTEND_PORT}:8080"